let name1 = prompt("What's your name?");
let name_prompt = document.querySelector(".name");
name_prompt.innerHTML = name1;
let coun1 = prompt("Where do you live?");
let coun_prompt = document.querySelector(".country");
coun_prompt.innerHTML = coun1;
let height1 = prompt("What's your height?");
let height_prompt = document.querySelector(".height");
height_prompt.innerHTML = height1;
